src/pension/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('retraite.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]
# Ajouter la configuration pour servir les fichiers statics pendant le developpement
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root = settings.MEDIA_ROOT
    )

src/retraite/urls.py
from django.urls import path
from .views import (retraite_home, dashboard_retraite, dashboard_prefecture, dashboard_employeur, dashboard_retraite_deces, dashboard_retraite_billetage,
                    dashboard_retraite_virement, etats_retraite, test_retraite)

app_name = 'retraite'

urlpatterns = [
    # Home
    path('', retraite_home.index, name= 'home'),
    path('retraite', retraite_home.retraite, name= 'retraite_home'),
    # dashboard Retraite
    path('retraite_liste', dashboard_retraite.dashboard_retraite_index, name= 'retraite_liste'),
    path('retraite/add', dashboard_retraite.add_retraite, name= 'retraite_add'),
    path('retraite/view/<int:nPension>/', dashboard_retraite.view_retraite, name= 'retraite_view'),
    path('retraite/edit/<int:nPension>/', dashboard_retraite.edit_retraite, name= 'retraite_edit'),
    path('retraite/delete/<int:nPension>/', dashboard_retraite.delete_retraite, name= 'retraite_delete'),
    # dashboard Prefecture
    path('prefecture_liste', dashboard_prefecture.dashboard_prefecture_index, name= 'prefecture_liste'),
    path('prefecture/add', dashboard_prefecture.add_prefecture, name= 'prefecture_add'),
    path('prefecture/edit/<str:codePrefecture>/', dashboard_prefecture.edit_prefecture, name= 'prefecture_edit'),
    path('prefecture/delete/<str:codePrefecture>/', dashboard_prefecture.delete_prefecture, name= 'prefecture_delete'),
    # dashboard Prefecture
    path('employeur_liste', dashboard_employeur.dashboard_employeur_index, name= 'employeur_liste'),
    path('employeur/add', dashboard_employeur.add_employeur, name= 'employeur_add'),
    path('employeur/edit/<str:codeEmployeur>/', dashboard_employeur.edit_employeur, name= 'employeur_edit'),
    path('employeur/delete/<str:codeEmployeur>/', dashboard_employeur.delete_employeur, name= 'employeur_delete'),
    # dashboard RetraiteDecès
    path('retraite_deces_liste', dashboard_retraite_deces.dashboard_retraite_deces_index, name= 'retraite_deces_liste'),
    path('retraite_deces/add', dashboard_retraite_deces.add_retraite_deces, name= 'retraite_deces_add'),
    path('retraite_deces/edit/<int:id>/', dashboard_retraite_deces.edit_retraite_deces, name= 'retraite_deces_edit'),
    path('retraite_deces/delete/<int:id>/', dashboard_retraite_deces.delete_retraite_deces, name= 'retraite_deces_delete'),
    # dashboard RetraiteBilletage
    path('retraite/billetage', dashboard_retraite_billetage.dashboard_retraite_billetage, name= 'retraite_billetage'),
    # dashboard RetraiteVirement
    path('retraite/virement_liste', dashboard_retraite_virement.dashboard_retraite_virement_index, name= 'retraite_virement_liste'),
    path('retraite_virement/add', dashboard_retraite_virement.add_retraite_virement, name= 'retraite_virement_add'),
    path('retraite_virement/edit/<int:id>/', dashboard_retraite_virement.edit_retraite_virement, name= 'retraite_virement_edit'),
    path('retraite_virement/delete/<int:id>/', dashboard_retraite_virement.delete_retraite_viremnt, name= 'retraite_virement_delete'),
    # états
    path('retraite/etats_liste', etats_retraite.retraite_etats, name='retraite_etats'),
    # test
    path('retraite/test', test_retraite.retraite_test, name='retraite_test'),
    ]

src/retraite/models/EcheancesRetraite.py
from django.db import models

class EcheancesRetraite(models.Model):
    dateecheance = models.DateField()
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.dateecheance}"

src/retraite/forms/EmployeurForm.py
from django import forms
from ..models import Employeur



class EmployeurForm(forms.ModelForm):
    class Meta:
        model = Employeur
        fields = (

            'codeEmployeur',
            'nomEmployeur',
        )

        widgets = {
            'codeEmployeur': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Numéro Employeur'}),
            'nomEmployeur': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nom de la Société'}),
        }

src/retraite/forms/PrefectureForm.py
from django import forms
from ..models import Prefecture



class PrefectureForm(forms.ModelForm):
    class Meta:
        model = Prefecture
        fields = (

            'codePrefecture',
            'nomPrefecture',
        )

        widgets = {
            'codePrefecture': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Numéro Assignation'}),
            'nomPrefecture': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nom Préfecture'}),
        }

src/retraite/forms/RetraiteDecesForm.py
from django import forms
from ..models import RetraiteDeces



class RetraiteDecesForm(forms.ModelForm):
    class Meta:
        model = RetraiteDeces
        fields = (

            'retraite',
            'dateDeces',
            'AssignationDefunt',
            'dateDeclaration',

        )

        widgets = {
            'AssignationDefunt': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Assignation du defunt'}),
            'retraite': forms.Select(attrs={'class': 'form-control'}),
            'dateDeces': forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Date de Décès'}),
            'dateDeclaration': forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Date de déclaration à la CNSS'}),
        }

src/retraite/views/dashboard_employeur.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404, redirect
from ..models.Employeur import Employeur
from django.contrib.auth.decorators import login_required
from ..forms.EmployeurForm import EmployeurForm
from django.contrib import messages



@login_required
def dashboard_employeur_index(request):
    # affichage de tout le contenu de préfecture
    employeur = Employeur.objects.all()

    # création du champ de recherche
    if request.method == 'GET':
        name = request.GET.get('recherche')
        if name != '' and name is not None:
            employeur = Employeur.objects.filter(codeEmployeur__contains=name)

        # création de la paggination
        paginator = Paginator(employeur.order_by('id'), per_page=10)
        page = request.GET.get('page', 1)
        try:
            employeur = paginator.get_page(page)
        except:
            employeur = paginator.get_page(1)

    return render(request, 'retraite/dashboard/dashboard_employeur_index.html', {'employeur': employeur})

@login_required
def add_employeur(request):
    if request.method == 'POST':
        employeur_form = EmployeurForm(request.POST)
        if employeur_form.is_valid():
            employeur_form.save()
            messages.success(request, "Ajouté avec succès!")
            return redirect('retraite:employeur_liste')
    else:
        employeur_form = EmployeurForm()

    return render(request, 'retraite/dashboard/add_employeur.html', {'employeur_form': employeur_form})

@login_required
def edit_employeur(request, codeEmployeur):
    employeur = get_object_or_404(Employeur, codeEmployeur=codeEmployeur)
    if request.method == 'POST':
        if request.POST.get('_method') == 'PUT':
            employeur_form = EmployeurForm(request.POST, instance=employeur)

            if employeur_form.is_valid():
                employeur_form.save()
                messages.success(request, "Modifié avec success !")
                return redirect('retraite:employeur_liste')
        else:
            employeur_form = EmployeurForm(instance=employeur)
    else:
        employeur_form = EmployeurForm(instance=employeur)

    return render(request, 'retraite/dashboard/add_employeur.html', {'employeur_form': employeur_form, 'employeur': employeur})

@login_required
def delete_employeur(request, codeEmployeur):
    employeur = get_object_or_404(Employeur, codeEmployeur=codeEmployeur)
    if request.method == 'POST':
        if request.POST.get('_method') == 'DELETE':
            employeur.delete()
            messages.success(request, "Supprimé avec success !")
            return redirect('retraite:employeur_liste')

src/retraite/views/dashboard_prefecture.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404, redirect
from ..models.Prefecture import Prefecture
from django.contrib.auth.decorators import login_required
from ..forms.PrefectureForm import PrefectureForm
from django.contrib import messages


@login_required
def dashboard_prefecture_index(request):
    # affichage de tout le contenu de préfecture
    prefecture = Prefecture.objects.all()

    # création du champ de recherche
    if request.method == 'GET':
        name = request.GET.get('recherche')
        if name != '' and name is not None:
            prefecture = Prefecture.objects.filter(codePrefecture__contains=name)

        # création de la paggination
        paginator = Paginator(prefecture.order_by('id'), per_page=10)
        page = request.GET.get('page', 1)
        try:
            prefecture = paginator.get_page(page)
        except:
            prefecture = paginator.get_page(1)

    return render(request, 'retraite/dashboard/dashboard_prefecture_index.html', {'prefecture': prefecture})

@login_required
def add_prefecture(request):
    if request.method == 'POST':
        prefecture_form = PrefectureForm(request.POST)
        if prefecture_form.is_valid():
            prefecture_form.save()
            messages.success(request, "Ajouté avec succès!")
            return redirect('retraite:prefecture_liste')
    else:
        prefecture_form = PrefectureForm()

    return render(request, 'retraite/dashboard/add_prefecture.html', {'prefecture_form': prefecture_form})

@login_required
def edit_prefecture(request, codePrefecture):
    prefecture = get_object_or_404(Prefecture, codePrefecture=codePrefecture)
    if request.method == 'POST':
        if request.POST.get('_method') == 'PUT':
            prefecture_form = PrefectureForm(request.POST, instance=prefecture)

            if prefecture_form.is_valid():
                prefecture_form.save()
                messages.success(request, "Modifié avec success !")
                return redirect('retraite:prefecture_liste')
        else:
            prefecture_form = PrefectureForm(instance=prefecture)
    else:
        prefecture_form = PrefectureForm(instance=prefecture)

    return render(request, 'retraite/dashboard/add_prefecture.html', {'prefecture_form': prefecture_form, 'prefecture': prefecture})

@login_required
def delete_prefecture(request, codePrefecture):
    prefecture = get_object_or_404(Prefecture, codePrefecture=codePrefecture)
    if request.method == 'POST':
        if request.POST.get('_method') == 'DELETE':
            prefecture.delete()
            messages.success(request, "Supprimé avec success !")
            return redirect('retraite:prefecture_liste')

src/retraite/views/dashboard_retraite.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404, redirect
from ..models.Retraite import Retraite
from django.contrib.auth.decorators import login_required
from ..forms.RetraiteForm import RetraiteForm
from django.contrib import messages
import os
from django.conf import settings

@login_required
def dashboard_retraite_index(request):
    # affichage de tout le contenu retraite
    retraite = Retraite.objects.all()

    #création du champ recherche
    if request.method == 'GET':
       name = request.GET.get('recherche')
       if name != '' and name is not None:
          retraite = Retraite.objects.filter(nPension__contains=name)


       # création de la pagination
       paginator= Paginator(retraite.order_by('id'), per_page=10)
       page = request.GET.get('page', 1)
       try:
          retraite = paginator.get_page(page)
       except:
          retraite = paginator.get_page(1)

    return render(request, 'retraite/dashboard/dashboard_retraite_index.html', {'retraite': retraite})

# création de la page d'ajout
@login_required
def add_retraite(request):
    if request.method == 'POST':
        retraite_form = RetraiteForm(request.POST, request.FILES)
        if retraite_form.is_valid():
            retraite_form.save()
            messages.success(request, "Ajouté avec succès!")
            return redirect('retraite:retraite_liste')
    else:
        retraite_form = RetraiteForm()

    return render(request, 'retraite/dashboard/add_retraite.html', {'retraite_form': retraite_form})

# création de la modification
@login_required
def edit_retraite(request, nPension):
    retraite = get_object_or_404(Retraite, nPension=nPension)
    old_image = retraite.image.path if retraite.image else None  # Stockez l'ancienne image

    if request.method == "POST":
        if request.POST.get('_method') == 'PUT':
            retraite_form = RetraiteForm(request.POST, request.FILES, instance=retraite)
            if retraite_form.is_valid():
                # Vérifiez si une nouvelle image a été téléchargée
                new_image = request.FILES.get('image')
                if new_image and old_image:
                    # Supprimez l'ancienne image
                    if os.path.exists(old_image):
                        os.remove(old_image)

                retraite_form.save()
                messages.success(request, "Modifié avec success !")
                return redirect('retraite:retraite_liste')
        else:
            retraite_form = RetraiteForm(instance=retraite)

    else:
        retraite_form = RetraiteForm(instance=retraite)
    return render(request, 'retraite/dashboard/add_retraite.html', {'retraite_form': retraite_form, 'retraite': retraite})



# création de la page de visualisation
@login_required
def view_retraite(request, nPension):
    retraite = get_object_or_404(Retraite, nPension=nPension)
    return render(request, 'retraite/dashboard/view_retraite.html', {'retraite': retraite})

# création de la suppression
@login_required
def delete_retraite(request, nPension):
    retraite = get_object_or_404(Retraite, nPension=nPension)
    if request.method == "POST":
        if request.POST.get('_method') == 'DELETE':
            if retraite.image:
                image_path = retraite.image.path
                if(os.path.exists(image_path)):
                    os.remove(image_path)
            retraite.delete()
            messages.success(request, "Enregistrement supprimé !")
            return redirect('retraite:retraite_liste')

src/retraite/views/dashboard_retraite_billetage.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404, redirect
from ..models.RetraiteDeces import RetraiteDeces
from ..models.RetraiteVirement import RetraiteVirement
from ..models.Retraite import Retraite
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import OuterRef, Subquery


@login_required
def dashboard_retraite_billetage(request):
    # Sous-requête pour obtenir les nPension dans RetraiteDeces
    retraite_deces_subquery = RetraiteDeces.objects.filter(
        retraite_id=OuterRef('id')
    ).values('retraite__nPension')

    # Sous-requête pour obtenir les nPension dans Virementretraite
    retraite_virement_subquery = RetraiteVirement.objects.filter(
        retraite_id=OuterRef('id')
    ).values('retraite__nPension')

    # Exclusion des retraites ayant un nPension dans RetraiteDeces ou Virementretraite
    retraites_disponibles = Retraite.objects.exclude(
        nPension__in=retraite_deces_subquery
    ).exclude(
        nPension__in=retraite_virement_subquery
    )

    # Calcul des totaux
    total_montantTrim = sum(r.montantTrim for r in retraites_disponibles)
    total_allocation = sum(r.allocation for r in retraites_disponibles)
    total_montantTotal = sum(r.montantTotal for r in retraites_disponibles)
    total_montantMensuel = sum(r.montantMensuel() for r in retraites_disponibles)
    total_montantComp = sum(r.montantComp for r in retraites_disponibles)
    total_montantPaye = sum(r.montantPaye() for r in retraites_disponibles)

    # création de la paggination
    paginator = Paginator(retraites_disponibles.order_by('id'), per_page=10)
    page = request.GET.get('page', 1)
    try:
        retraites_disponibles = paginator.get_page(page)
    except:
        retraites_disponibles = paginator.get_page(1)

    context = {
        'retraites_disponibles': retraites_disponibles,
        'totaux': {
            'montantTrim': total_montantTrim,
            'allocation': total_allocation,
            'montantTotal': total_montantTotal,
            'montantMensuel': total_montantMensuel,
            'montantComp': total_montantComp,
            'montantPaye': total_montantPaye,
        },
    }

    return render(request, 'retraite/dashboard/retraite_billetage.html', context)

src/retraite/views/retraite_home.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required



@login_required
def index(request):
    return render(request, 'retraite/index.html')

@login_required
def retraite(request):
    return render(request, 'retraite/retraite_home.html')

src/templates/retraite/dashboard/dashboard_employeur_index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
<!-- recherche et ajout -->
  <div class="container mt-5">
    <form class="d-flex" role="search">
      <input class="form-control me-2" type="search" placeholder="Rechercher" name="recherche">
      <button class="btn btn-outline-warning" type="submit">Rechercher</button>
      <a href="{% url 'retraite:employeur_add' %}" class="btn btn-success mx-2" type="button">Ajouter</a>
    </form>
  </div>


<!-- Section tableau Retraite -->
<section>
  <div class="container mt-3">
  <div class="table-responsive">
    <table class="table table-hover table-sm caption-top">
      <caption>Dashboard Employeur</caption>
      <thead>
        <tr>
          <th scope="col">N°</th>
          <th scope="col">N° Employeur</th>
          <th scope="col">Nom Employeur</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
      {% for employeur in employeur %}
        <tr>
          <th scope="row">{{ employeur.id }}</th>
          <td>{{ employeur.codeEmployeur }}</td>
          <td>{{ employeur.nomEmployeur }}</td>
          <td>
            <div class="d-flex gap-2">

              <a href="{% url 'retraite:employeur_edit' employeur.codeEmployeur %}" class="btn btn-secondary btn-sm" data-bs-toggle="tooltip" data-bs-placement="bottom" title="modifier"><i class="bi bi-pencil-square"></i></a>
              <button class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#supprimer{{ employeur.codeEmployeur }}"><i class="bi bi-trash3"></i></button>
                <div class="modal fade" id="supprimer{{ employeur.codeEmployeur }}" tabindex="-1" data-bs-backdrop="static">
                  <div class="modal-dialog modal-dialog-centered ">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title">Supprimer un employeur</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                      </div>
                      <div class="modal-body">
                        <p class="m-0">Voulez-vous vraiment supprimer l'employeur n° {{ employeur.codeEmployeur}} ? </p>
                      </div>
                      <form action="{% url 'retraite:employeur_delete' employeur.codeEmployeur %}" method="post">
                        {% csrf_token %}
                      <div class="modal-footer">
                        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Annuler</button>

                        <input type="hidden" name="_method" value="DELETE">
                        <button class="btn btn-danger">Supprimer</button>

                      </div>
                      </form>
                    </div>
                  </div>
                </div>
            </div>
          </td>
        </tr>
      {% endfor %}
      </tbody>

    </table>
  </div>
    {% include "retraite/partials/paginator.html" with datas=employeur %}
</div>

</section>

{% endblock %}

src/templates/retraite/dashboard/dashboard_prefecture_index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
<!-- recherche et ajout -->
  <div class="container mt-5">
    <form class="d-flex" role="search">
      <input class="form-control me-2" type="search" placeholder="Rechercher" name="recherche">
      <button class="btn btn-outline-warning" type="submit">Rechercher</button>
      <a href="{% url 'retraite:prefecture_add' %}" class="btn btn-success mx-2" type="button">Ajouter</a>
    </form>
  </div>


<!-- Section tableau Retraite -->
<section>
  <div class="container mt-3">
  <div class="table-responsive">
    <table class="table table-hover table-sm caption-top">
      <caption>Dashboard Préfecture</caption>
      <thead>
        <tr>
          <th scope="col">N°</th>
          <th scope="col">codePrefecture</th>
          <th scope="col">nomPrefecture(s)</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
      {% for prefecture in prefecture %}
        <tr>
          <th scope="row">{{ prefecture.id }}</th>
          <td>{{ prefecture.codePrefecture }}</td>
          <td>{{ prefecture.nomPrefecture }}</td>
          <td>
            <div class="d-flex gap-2">

              <a href="{% url 'retraite:prefecture_edit' prefecture.codePrefecture %}" class="btn btn-secondary" data-bs-toggle="tooltip" data-bs-placement="bottom" title="modifier"><i class="bi bi-pencil-square"></i></a>
              <button class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#supprimer{{ prefecture.codePrefecture }}"><i class="bi bi-trash3"></i></button>
                <div class="modal fade" id="supprimer{{ prefecture.codePrefecture }}" tabindex="-1" data-bs-backdrop="static">
                  <div class="modal-dialog modal-dialog-centered ">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title">Supprimer une prefecture</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                      </div>
                      <div class="modal-body">
                        <p class="m-0">Voulez-vous vraiment supprimer la préfecture n° {{ prefecture.codePrefecture }} ? </p>
                      </div>
                      <form action="{% url 'retraite:prefecture_delete' prefecture.codePrefecture %}" method="post">
                        {% csrf_token %}
                      <div class="modal-footer">
                        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Annuler</button>

                        <input type="hidden" name="_method" value="DELETE">
                        <button class="btn btn-danger">Supprimer</button>

                      </div>
                        </form>
                    </div>
                  </div>
                </div>
            </div>
          </td>
        </tr>
      {% endfor %}
      </tbody>

    </table>
  </div>
    {% include "retraite/partials/paginator.html" with datas=prefecture %}
</div>

</section>

{% endblock %}

src/templates/retraite/dashboard/dashboard_retraite_index.html
{% extends 'base.html' %}
{% load static %}
{% load montant_price %}


{% block content %}
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
<!-- recherche et ajout -->
  <div class="container mt-5">
    <form class="d-flex" role="search">
      <input class="form-control me-2" type="search" placeholder="Rechercher" name="recherche">
      <button class="btn btn-outline-warning" type="submit">Rechercher</button>
      <a href="{% url 'retraite:retraite_add' %}" class="btn btn-success mx-2" type="button">Ajouter</a>
    </form>
  </div>


<!-- Section tableau Retraite -->
<section>
  <div class="container mt-3">
  <div class="table-responsive">
    <table class="table table-hover table-sm caption-top">
      <caption>Dashboard Retraites</caption>
      <thead>
        <tr>
          <th scope="col">N°</th>
          <th scope="col">Titre</th>
          <th scope="col">Prénom(s)</th>
          <th scope="col">Nom</th>
          <th scope="col">Type</th>
          <th scope="col">N° Pension</th>
          <th scope="col">Employeur</th>
          <th scope="col">MontTrimTotal</th>
          <th scope="col">MontMens</th>
          <th scope="col">Observation</th>
          <th scope="col">Image</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
      {% for retraite in retraite %}
        <tr>
          <th scope="row">{{ retraite.id }}</th>
          <td>{{ retraite.titre }}</td>
          <td>{{ retraite.prenom }}</td>
          <td>{{ retraite.nom }}</td>
          <td>{{ retraite.type }}</td>
          <td>{{ retraite.nPension }}</td>
          <td>{{ retraite.employeur.nomEmployeur }}</td>
          <td>{{ retraite.montantTotal|format_milliers }}</td>
          <td>{{ retraite.montantMensuel|format_milliers }}</td>
          <td>{{ retraite.Observation }}</td>
          <td width="20"><img src="/media/{{ retraite.image }}" width="20" height="20"></td>
          <td>
            <div class="d-flex gap-1">
              <a href="{% url 'retraite:retraite_view' retraite.nPension %}" class="btn btn-success btn-sm" data-bs-toggle="tooltip" data-bs-placement="bottom" title="detail"><i class="bi bi-eye"></i></a>
              <a href="{% url 'retraite:retraite_edit' retraite.nPension %}" class="btn btn-secondary btn-sm" data-bs-toggle="tooltip" data-bs-placement="bottom" title="modifier"><i class="bi bi-pencil-square"></i></a>

                <button class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#supprimer{{ retraite.nPension }}"><i class="bi bi-trash3"></i></button>
                <div class="modal fade" id="supprimer{{ retraite.nPension }}" tabindex="-1" data-bs-backdrop="static">
                  <div class="modal-dialog modal-dialog-centered ">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title">Supprimer un retraite</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal">

	                    </button>
                      </div>
                      <div class="modal-body">
                        <p class="m-0">Voulez-vous vraiment supprimer la retraite n° {{ retraite.nPension }} ? </p>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Annuler</button>
                      <form action="{% url 'retraite:retraite_delete' retraite.nPension %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="_method" value="DELETE">
                        <button class="btn btn-danger">Supprimer</button>
                      </form>
                      </div>
                    </div>
                  </div>
                </div>
            </div>
          </td>
        </tr>
      {% endfor %}
      </tbody>

    </table>
  </div>
    {% include "retraite/partials/paginator.html" with datas=retraite %}
</div>

</section>

{% endblock %}